---
# Start the demo project in Docker for a sanity check
# Note: It's expected that you have ran the make command to build the base image
# and it exists in your local Docker registry

services:

  postgres:
    image: postgres:15-alpine
    env_file:
      - "./demo/api/.env.test"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  api:
    build:
      context: ./demo/api
    image: modelw-base-test-api:latest
    depends_on:
      front:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - "./demo/api/.env.test"
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8000/back/admin/login/"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    command: >
      sh -c "
      modelw-docker run python manage.py migrate &&
      modelw-docker serve
      "

  front:
    build:
      context: ./demo/front
    image: modelw-base-test-front:latest
    env_file:
      - "./demo/front/.env.test"
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/non-cms/"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  router:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      front:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - ./demo/api/bdd/_infrastructure/mock-digital-ocean-router.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://router:80/favicon.png"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
