[tool.poetry]
name = "modelw-docker"
version = "2026.4.0"
description = "Utility to simplify Dockerfiles"
authors = ["Rémy Sanchez <remy.sanchez@hyperthese.net>"]
license = "WTFPL"
readme = "README.md"
packages = [{include = "model_w/docker", from = "src"}]
repository = "https://github.com/ModelW/docker/"
documentation = "https://github.com/ModelW/docker/"
homepage = "https://github.com/ModelW/docker/"
keywords = ["docker", "django", "nuxt", "dockerfile"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Utilities",
    "Framework :: Django",
    "Framework :: Wagtail",
]

[tool.poetry.scripts]
modelw-docker = "model_w.docker.__main__:__main__"

[tool.poetry.dependencies]
python = "^3.14"
setuptools = "*"
psutil = "^7.2.1"
colorama = "^0.4.6"
typefit = "^1.0.0"


[tool.poetry.group.dev.dependencies]
monoformat = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
