name: Build Docker Image

on:
    push:
        branches:
            - develop

jobs:
    docker:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: image
        steps:
            - name: Print Docker username
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                  echo DOCKER_USERNAME=$DOCKER_USERNAME
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/base:${{ github.branch }}
