name: Build on push

on:
    push:
        branches:
            - "develop"
            - "master"
            - "support/**"

jobs:
    call-build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Call build-image
              uses: ./.github/actions/build-image
              with:
                  ref: ${{ github.ref }}
