name: Build on schedule

on:
    schedule:
        - cron: "42 */3 * * *"
    workflow_dispatch:

jobs:
    call-build-image:
        uses: ./.github/workflows/build-image.yml
        strategy:
            max-parallel: 1
            matrix:
                ref: [ "support/2023.03", "support/2023.07", "support/2024.04",  "support/2024.07" ]
        with:
            ref: ${{ matrix.ref }}
        secrets: inherit
