name: Build on schedule

on:
    schedule:
        - cron: "42 0 * * *"

jobs:
    call-build-image:
        uses: ./.github/workflows/build-image.yml
        strategy:
            max-parallel: 1
            matrix:
                ref: [ "support/2023.03", "support/2023.07" ]
        with:
            ref: ${{ matrix.ref }}
        secrets: inherit
