name: Build Docker Image

on:
    push:
        branches:
            - develop
            - master
            - support/*

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Extract branch name
              shell: bash
              run: |
                  echo GITHUB_ENV="$GITHUB_ENV"
                  echo GITHUB_OUTPUT="$GITHUB_OUTPUT"
                  echo "DOCKER_TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -E 's/^support\///' | sed 's/^master$/latest/')" >> $GITHUB_ENV
                  cat $GITHUB_ENV
              id: extract_branch
            - name: Print debug info
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_TAG: ${{ env.DOCKER_TAG }}
              run: |
                  echo DOCKER_TAG=$DOCKER_TAG
                  echo DOCKER_USERNAME=$DOCKER_USERNAME
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./image
                  push: true
                  tags: |-
                      ${{ secrets.DOCKER_USERNAME }}/base:${{ env.DOCKER_TAG }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
