name: Build on schedule

on:
    schedule:
        - cron: "42 */3 * * *"
    workflow_dispatch:
        inputs:
            skip_check:
                description: 'Skip checks during build'
                required: false
                default: true
                type: boolean

jobs:
    call-build-image:
        uses: ./.github/workflows/build-image.yml
        strategy:
            max-parallel: 1
            matrix:
                ref:
                    [
                        "support/2025.01",
                        "support/2025.04",
                        "support/2025.07",
                        "support/2025.10",
                    ]
        with:
            ref: ${{ matrix.ref }}
            skip_check: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.skip_check == 'true' || github.event.inputs.skip_check == true) }}
        secrets: inherit
