name: Build on push

on:
    push:
        branches:
            - "develop"
            - "master"
            - "support/**"

jobs:
    call-build-image:
        uses: ./.github/workflows/build-image.yml
        with:
            ref: ${{ github.ref }}
