name: Build on schedule

on:
    schedule:
        - cron: "42 */3 * * *"
    workflow_dispatch:

jobs:
    call-build-image:
        uses: ./.github/workflows/build-image.yml
        strategy:
            max-parallel: 1
            matrix:
                ref:
                    [
                        "support/2024.10",
                        "support/2025.01",
                        "support/2025.04",
                        "support/2025.07",
                    ]
        with:
            ref: ${{ matrix.ref }}
        secrets: inherit
